language: generic
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - openssl
    - pandoc
    - wget
before_script:
- wget https://github.com/jgm/pandoc/releases/download/2.1.2/pandoc-2.1.2-1-amd64.deb
- sudo dpkg -i pandoc-2.1.2-1-amd64.deb
script: bash deploy/travis-build.sh
env:
  global:
  - ENCRYPTION_LABEL: "143974d01293"
  - COMMIT_AUTHOR_EMAIL: "mo@neva.li"
