language: generic
dist: trusty
addons:
  apt:
    packages:
    - pandoc
    - openssl
script: bash deploy/travis-build.sh
env:
  global:
  - ENCRYPTION_LABEL: "143974d01293"
  - COMMIT_AUTHOR_EMAIL: "mo@neva.li"
